// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// static/action.tmpl
// static/article.css
// static/dir.css
// static/dir.js
// static/dir.tmpl
// static/favicon.ico
// static/jquery-ui.js
// static/notes.css
// static/notes.js
// static/slide.tmpl
// static/slides.js
// static/styles.css
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// actionTmpl reads file data from disk. It returns an error on failure.
func actionTmpl() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/action.tmpl"
	name := "action.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// articleCss reads file data from disk. It returns an error on failure.
func articleCss() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/article.css"
	name := "article.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dirCss reads file data from disk. It returns an error on failure.
func dirCss() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/dir.css"
	name := "dir.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dirJs reads file data from disk. It returns an error on failure.
func dirJs() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/dir.js"
	name := "dir.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dirTmpl reads file data from disk. It returns an error on failure.
func dirTmpl() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/dir.tmpl"
	name := "dir.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconIco reads file data from disk. It returns an error on failure.
func faviconIco() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/favicon.ico"
	name := "favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jqueryUiJs reads file data from disk. It returns an error on failure.
func jqueryUiJs() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/jquery-ui.js"
	name := "jquery-ui.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// notesCss reads file data from disk. It returns an error on failure.
func notesCss() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/notes.css"
	name := "notes.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// notesJs reads file data from disk. It returns an error on failure.
func notesJs() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/notes.js"
	name := "notes.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// slideTmpl reads file data from disk. It returns an error on failure.
func slideTmpl() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/slide.tmpl"
	name := "slide.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// slidesJs reads file data from disk. It returns an error on failure.
func slidesJs() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/slides.js"
	name := "slides.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// stylesCss reads file data from disk. It returns an error on failure.
func stylesCss() (*asset, error) {
	path := "/Users/cj/Documents/Work/mypresent/static/styles.css"
	name := "styles.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"action.tmpl":  actionTmpl,
	"article.css":  articleCss,
	"dir.css":      dirCss,
	"dir.js":       dirJs,
	"dir.tmpl":     dirTmpl,
	"favicon.ico":  faviconIco,
	"jquery-ui.js": jqueryUiJs,
	"notes.css":    notesCss,
	"notes.js":     notesJs,
	"slide.tmpl":   slideTmpl,
	"slides.js":    slidesJs,
	"styles.css":   stylesCss,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"action.tmpl":  &bintree{actionTmpl, map[string]*bintree{}},
	"article.css":  &bintree{articleCss, map[string]*bintree{}},
	"dir.css":      &bintree{dirCss, map[string]*bintree{}},
	"dir.js":       &bintree{dirJs, map[string]*bintree{}},
	"dir.tmpl":     &bintree{dirTmpl, map[string]*bintree{}},
	"favicon.ico":  &bintree{faviconIco, map[string]*bintree{}},
	"jquery-ui.js": &bintree{jqueryUiJs, map[string]*bintree{}},
	"notes.css":    &bintree{notesCss, map[string]*bintree{}},
	"notes.js":     &bintree{notesJs, map[string]*bintree{}},
	"slide.tmpl":   &bintree{slideTmpl, map[string]*bintree{}},
	"slides.js":    &bintree{slidesJs, map[string]*bintree{}},
	"styles.css":   &bintree{stylesCss, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
